[package]
name = "wp-log"
version = "0.3.0"
edition = "2024"
license = "Elastic-2.0"
authors = ["WarpParse Dev Team"]
description = "Structured logging macros plus log4rs configuration helpers for WarpParse services"
readme = "README.md"
repository = "https://github.com/wp-labs/wp-log"
homepage = "https://github.com/wp-labs/wp-log"
documentation = "https://docs.rs/wp-log"
keywords = ["logging", "log4rs", "macro", "configuration", "warpparse"]
categories = ["config", "development-tools::debugging"]


[lib]
name = "wp_log"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
toml = "1.0"
orion-variate= "0.12"
orion-error = "0.7"
orion_conf =  { version = "0.6", features = ["toml"]}
derive_more = "2.1"

unicode-segmentation = "1.12"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0"
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
strum_macros = "0.27"
anyhow = "1.0"
log4rs = { version = "1.4", features = ["gzip"] }
getset = "0.1"

[dev-dependencies]

[features]
default = ["std"]
std = []
